### ISSUE TITLE
Allow SSL Context customization

### ISSUE THREAD

**Issue by mp911de** [mirromutth/r2dbc-mysql#100]
The driver should accept a customization function for the SSL context, such as `Function<SslContextBuilder, SslContextBuilder>` to allow detailed and fine-grained configuration of the SSL context.

A typical use-case is provisioning of certificates beyond what `MysqlConfiguration` currently allows. Certificates may originate from other sources (i.e. being downloaded or provided by some non-file instance). We have a similar feature in R2DBC Postgres, see r2dbc/r2dbc-postgresql#191.

For customization to properly work, it's required that the SSL context gets created on each connect attempt.

See also GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#164 that requires such a configuration mechanism.

**Comment by mirromutth** [comment]
It's resolved by PR and published to `0.8.2.BUILD-SNAPSHOT`, target version is `0.8.2.RELEASE`.
