### ISSUE TITLE
Allow to add a `codec`

### ISSUE THREAD

**Issue by jinsankim** [mirromutth/r2dbc-mysql#102]
## Motivation

I'd like to suggest to allow to add a `codec`. Referencing `r2dbc-postgresql`, it allows to add a `codec` via `CodecRegistry`.

## Reference
* [postgresql/codec/DefaultCodecs.java](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/DefaultCodecs.java)
* [postgresql/codec/CodecRegistry.java](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/CodecRegistry.java)

**Comment by mirromutth** [comment]
It is supported by PR and deploy to `0.8.2.BUILD-SNAPSHOT`, target version is `0.8.2.RELEASE`.
