### ISSUE TITLE
Dialect Issue

### ISSUE THREAD

**Issue by sobhan-sai** [mirromutth/r2dbc-mysql#104]
Cannot determine a dialect for MySQL using dev.miku.r2dbc.mysql.MySqlConnectionFactory@4650a407. Please provide a Dialect.

**Comment by sobhan-sai** [comment]
@mirromutth 
Cannot determine a dialect for MySQL using dev.miku.r2dbc.mysql.MySqlConnectionFactory@4650a407. Please provide a Dialect.

**Comment by mirromutth** [comment]
Hi, there.

The feature of the dialect (see [`DialectResolver`](https://github.com/spring-projects/spring-data-r2dbc/blob/7ec3d28b17ef4c4a6c77b355c777cccf9519cb10/src/main/java/org/springframework/data/r2dbc/dialect/DialectResolver.java)) was provided by Spring Data R2DBC, but maybe I can help you. Which R2DBC MySQL and Spring Data R2DBC versions did you use?

**Comment by sobhan-sai** [comment]
@mirromutth 
Hi Sir,
Thanks for the response.
I am using the following dependencies and the configuration file for MySqlConnectionConfiguration. Please hep me on this. Thank you
<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-r2dbc</artifactId>
			<version>1.0.0.M1</version>
		</dependency>
<dependency>
			<groupId>dev.miku</groupId>
			<artifactId>r2dbc-mysql</artifactId>
			<version>0.8.1.RELEASE</version>
		</dependency>
package com.feedbackmanagement.authenticationandauthorization.configuration;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.r2dbc.config.AbstractR2dbcConfiguration;
import org.springframework.data.r2dbc.repository.config.EnableR2dbcRepositories;

import dev.miku.r2dbc.mysql.MySqlConnectionConfiguration;
import dev.miku.r2dbc.mysql.MySqlConnectionFactory;
import io.r2dbc.spi.ConnectionFactory;
import io.r2dbc.spi.ConnectionFactoryMetadata;


@Configuration
@EnableR2dbcRepositories("com.feedbackmanagement.authenticationandauthorization.repository")
public class MysqlConfiguration extends AbstractR2dbcConfiguration  {

	@Override
	@Bean
	public ConnectionFactory connectionFactory() {
		MySqlConnectionConfiguration configuration = MySqlConnectionConfiguration.builder().host("127.0.0.1")
				.username("root").port(3306) // optional, default 3306
				.password("root123") // optional, default null, null means has no password
				.database("feedbackmanagement")// optional, default null, null means not specifying the database
				.build();
		ConnectionFactory connectionFactory = MySqlConnectionFactory.from(configuration);
		return connectionFactory;
	}

}

**Comment by mp911de** [comment]
Please upgrade to Spring Data R2DBC 1.0.0.RELEASE.

**Comment by sobhan-sai** [comment]
@mirromutth 
Hi Sir,
Thank you so much for your help. The error got resolved now.  But now I am getting another error.:
Warning: Connection has been closed by peer 
Caused by: io.r2dbc.spi.R2dbcPermissionDeniedException: Access denied for user 'root'@'localhost' (using password: NO). 
Please help me regarding this.
Thank you.

**Comment by sobhan-sai** [comment]
> Please upgrade to Spring Data R2DBC 1.0.0.RELEASE.

Hi Sir,
Thank you so much for your help. The error got resolved now. But now I am getting another error.:
Warning: Connection has been closed by peer
Caused by: io.r2dbc.spi.R2dbcPermissionDeniedException: Access denied for user 'root'@'localhost' (using password: NO).
Please help me regarding this.
Thank you.

**Comment by mp911de** [comment]
You might want to educate yourself if MySQL authentication and permissions. Assuming username and password are correctly set, there’s nothing we can do here.

**Comment by mirromutth** [comment]
Yes, as mp911de said. This exception message means your database root superuser has a password. For MySQL, password is required when the user has a password. But looks like password has been not set in driver. See also README, it shows three ways to set the user's password.

**Comment by mirromutth** [comment]
I'm trying to close this issue due to inactivity.
