### ISSUE TITLE
Should support data type GEOMETRY?

### ISSUE THREAD

**Issue by mirromutth** [mirromutth/r2dbc-mysql#11]
`GEOMETRY` is a special data type, I have not been find jdbc related support, should support data type `GEOMETRY`?

**Comment by mp911de** [comment]
Geometry and JSON support are not reflected in JDBC. These are vendor-specific extension. For now, JSON with R2DBC is just pass-thru as most databases treat JSON as some sort of text field.

**Comment by mirromutth** [comment]
`GEOMETRY` will be treated as a `BLOB` for now. This issue will be reopened if there is a change in feature.
