### ISSUE TITLE
Does support log output like jpa mybatis  select field1,field2 from table where condition

### ISSUE THREAD

**Issue by yadong2000** [mirromutth/r2dbc-mysql#112]
Does support log output like jpa mybatis  select field1,field2 from table where  condition

**Comment by mirromutth** [comment]
Hi there,

Great thanks for your suggestion, apologies for the late reply.

I'm trying to do a feature similar to [r2dbc-mssql QueryLogger](https://github.com/r2dbc/r2dbc-mssql/blob/5868d7354c8701bf4b17c63c9570062bacd9d0be/src/main/java/io/r2dbc/mssql/QueryLogger.java)

I'm not sure if the driver need `BindingLogger` (like r2dbc-postgresql). So `BindingLogger` will not be supported. If anyone needs it, please create a new ticket.
