### ISSUE TITLE
SELECT  IN  parameter encode fail

### ISSUE THREAD

**Issue by hero-zhanghao** [mirromutth/r2dbc-mysql#115]
I used spring data r2dbc as a query and used the following method：
`
Flux<Table> findAllByTypeIn(List<Integer> types);
`
and 
`
Flux<Table> findAllByTypeIn(Set<Integer> types);
`
The following exception occurred. When I was at the breakpoint, I found that the parameter passed in was of type ArrayList, but I didn't know what the problem was .
`
java.lang.IllegalArgumentException: Cannot encode value of type 'class java.util.ArrayList'
	at dev.miku.r2dbc.mysql.codec.DefaultCodecs.encode(DefaultCodecs.java:182) ~[r2dbc-mysql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
`

Thanks for all the answers.

**Comment by mp911de** [comment]
This is a bug in Spring Data R2DBC and not a driver issue.

**Comment by hero-zhanghao** [comment]
@mp911de  
I saw that the corresponding problem was solved 2 days ago. Which version will it be applied in?
And thanks a lot, I got it running with the code below
`
@Query("select * from table where type in (:types)")
    Flux<Table> findAllByType(Set<Integer> types);
`

**Comment by mp911de** [comment]
It will be shipped with Spring Data R2DBC 1.1.1.RELEASE (transitively fixed in Spring Data Relational 2.0.1.RELEASE).
