### ISSUE TITLE
Cannot encode list of strings

### ISSUE THREAD

**Issue by garrychnca** [mirromutth/r2dbc-mysql#120]
In Spring Data R2DBC 1.1.0.RELEASE they support query deviation in `Repository`. For instance,

```java
public interface PersonRepository extends R2dbcRepository<PersonEntity, Long> {

    Mono<Void> deleteByNameIn(Collection<String> names);
}
```

When I tried the above repo with r2dbc-mysql setup, it encountered problem saying `Cannot encode value of type 'ArrayList'`.

The execution path is: `DefaultDatabaseClient#bindByIndex` -> `Statement#bind` -> `ParameterizedStatementSupport#bind` (r2dbc-mysql) -> `DefaultCodecs#encode` (r2dbc-mysql)

I see that you have the `StringArrayCodec`, so I changed the above repo to:

```java
public interface PersonRepository extends R2dbcRepository<PersonEntity, Long> {

    Mono<Void> deleteByNameIn(String[] names);
}
```

This time seems like Spring Data is not passing the array down to r2dbc-mysql properly as the value `DefaultCodecs#encode` receives is `class java.lang.String`.

When I use the `String[]` as the parameter type my IDE (Jetbrains with Spring support) even tells me:

> Expected parameter types: Collection  
> Inspection info: Spring Data Repository Method Parameters errors.

So I guess Spring Data repository query deviation does not support array parameter.

**Conclusion:** can you add codec support for `Collection` and `List`?

**Comment by mp911de** [comment]
That’s a Spring Data R2DBC issue that was fixed in version 1.1.1.RELEASE (see https://github.com/spring-projects/spring-data-r2dbc/issues/3619.

**Comment by garrychnca** [comment]
@mp911de I think the link you responded should be: https://github.com/spring-projects/spring-data-r2dbc/issues/361? issues/3619 does not exist.

**Comment by mp911de** [comment]
Yes, that’s the one. Something went wrong when pasting the link.

**Comment by mirromutth** [comment]
I'm trying to close this issue because the problem has been solved from an external project. Great thanks for Spring Data R2DBC team!
