### ISSUE TITLE
Unable to create a ConnectionFactory for 'ConnectionFactoryOptions options={}' . Available drivers: [ sqlserver ]

### ISSUE THREAD

**Issue by freeAgainFor1314** [mirromutth/r2dbc-mysql#141]
can't create directly connection occure the title issue.

**Comment by mp911de** [comment]
`Available drivers: [ sqlserver ]` means that the MySQL driver isn't on the class path.

**Comment by mirromutth** [comment]
As @mp911de said, maybe you should check your `pom.xml`, `build.gradle` (or others configuration about build)

Due to inactivity, I try to close this issue. If there are still any problems, please reopen this issue.
