### ISSUE TITLE
How to use preparestatement

### ISSUE THREAD

**Issue by YeautyYE** [mirromutth/r2dbc-mysql#146]
I want to use preparestatement in `insert`。
But when I use by spring-r2dbc(https://docs.spring.io/spring-data/r2dbc/docs/1.2.0-M2/reference/html/#r2dbc.datbaseclient.binding) ，it is a long concatenated string 。
e.g.
`REPLACE INTO table (id,name) VALUES (1,'Yeauty')`

**Comment by mirromutth** [comment]
Set option `useServerPrepareStatement` as enabled. See README.md.

See also #92, #96 .

I'm closing this issue, if there still have problem, please reopen this issue.
