### ISSUE TITLE
Consider JSON as pass-thru

### ISSUE THREAD

**Issue by mp911de** [mirromutth/r2dbc-mysql#15]
JSON mapping is typically an application-level concern (JSON-P, JSON-B) because all transformations and bindings are reflected on application or client-level. Having support directly in the driver comes with several drawbacks as drivers need to either commit to a single library or provide support for multiple implementations (Jackso, GSON, Apache Johnzon). This isn't typically the thing you want to deal with.
Also, most JSON libraries work with blocking streams (`InputStream`, `OutputStream`) that is not Reactive-friendly.

Another approach would be to provide an extensible codec registry and optional codecs that users can register.

**Comment by mirromutth** [comment]
Ok, I will remove JSON support and type `JSON` will be treated as a `VARCHAR`.

**Comment by mirromutth** [comment]
JSON support has removed. See `StringConverter` in `io.github.mirromutth.r2dbc.mysql.converter`.
