### ISSUE TITLE
Add Codec for java.sql.Timestamp

### ISSUE THREAD

**Issue by papahigh** [mirromutth/r2dbc-mysql#151]
Hi,

I'm getting the following error `Cannot encode value of type 'class java.sql.Timestamp'` for a `java.sql.Timestamp` value.
Could you please add a codec for this case?

Thanks

**Comment by mp911de** [comment]
R2DBC isn't affiliated with `java.sql` at all. There's no need to pull in the JDBC module. Also, from a Java modules perspective, depending on JDBC sends the wrong signals. R2DBC embraces JSR-310 types which are a way better fit than the broken JDBC types where timezones contribute to additional confusion.

**Comment by papahigh** [comment]
@mp911de Hi Mark!
I'm trying `r2dbc-mysql` with [micronaut-r2dbc](https://github.com/micronaut-projects/micronaut-r2dbc).
And looks like `micronaut` converts any date-related class to `java.sql.Timestamp`. (I'm using **java.time** classes).
Because of the missing codec, I got runtime exceptions.

Please take a look at PR  #152. I added codecs for  `java.sql.Timestamp` as well as for `java.util.Date` which is a superclass for legacy dates. With this change, everything works fine.

**Comment by papahigh** [comment]
@mp911de Thanks, I'll open a PR in `micronaut` then.
