### ISSUE TITLE
Some Questions about Custom Codec

### ISSUE THREAD

**Issue by btakeya** [mirromutth/r2dbc-mysql#154]
Hi, I'm writing to ask something about defining custom codec.
* Environment is,
  * Spring boot 2.3.4
  * Kotlin (java compat w/ 1.8)
  * R2DBC-MySQL 0.8.2 (dev.miku:r2dbc-mysql:0.8.2.RELEASE)
  * if any other is needed, just let me know :)
* First, I made a table on MySQL DB like this:
  ```sql
  CREATE TABLE tmp
  (
      tmp_id BIGINT AUTO_INCREMENT COMMENT 'PK' PRIMARY KEY,
      name VARCHAR(15) NULL COMMENT 'name',
      attr JSON NULL COMMENT 'attr',
      createdAt DATETIME(6) NULL,
      updatedAt DATETIME(6) NULL
  );
  ```
  as well as, defined a class for `tmp` like this:
  ```kotlin
  @Table("tmp")
  data class TmpRecord(
      @Id
      @Column("tmp_id")
      val id: Long,

      val name: String,

      val attr: Map<String, Any?>
  )
  ```
  thus, to parse `tmp.attr` properly, I need to a codec handles `JSON String` <-> `Map<String, Any>` (Actually, parse in `String` does well surely)
* On your kindly doc (README.md), show me the way to parse JSON by introducing `Codec`. (It really helps! Thanks)
  I tried to implement my `custom Codec` class according to this, but cannot find `dev.miku.r2dbc.mysql.codec.Codec`. I think it comes from modifier of `Codec` (https://github.com/btakeya/r2dbc-mysql/blob/main/src/main/java/dev/miku/r2dbc/mysql/codec/Codec.java#L30). If it is changed to be with public modifier, I can implement this class I thought. (If your intention isn't to restrict only provided classes can implement `Codec`)

**Comment by btakeya** [comment]
also, I'd like to inform I tested w/ package is applied #155 and I could implement my custom codec.

**Comment by btakeya** [comment]
some integration tests are failed, but seems that it comes from authorization.
```(error message: Both root password and superuser are empty, must contains one superuser)```

**Comment by btakeya** [comment]
note that, in some other r2dbc drivers (such as [google spanner](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/blob/master/cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codec.java#L24), [maria db](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/master/src/main/java/org/mariadb/r2dbc/codec/Codec.java#L23), [postgresql](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/codec/Codec.java#L33)), `Codec` interface is defined as public.

**Comment by btakeya** [comment]
Hi @mirromutth,
Could you tell me whether it can be fixed?

**Comment by btakeya** [comment]
I think I can close this issue as #155 is merged. Thanks @mirromutth

**Comment by arron-shin** [comment]
@mirromutth Hi, Do you have a release plan? This is absolutely necessary.
