### ISSUE TITLE
Client never close

### ISSUE THREAD

**Issue by mirromutth** [mirromutth/r2dbc-mysql#17]
Looks like `conntion.outbound().sendObject(obj).then()` will never complete, so `ReactNettyClient.close()` can not close the `connection` because it always waits for send-to-complete.

Connection need be close after exit message sent, even has no send complete signal.

@mp911de I am not sure it is right, would `NettyOutbound.sendObject(xxx).then()` has complete? Thx for your help.

**Comment by mp911de** [comment]
It completes after sending. Ideally, add a `LoggingHandler` to inspect what's going on.

R2DBC Postgres uses the same pattern (see https://github.com/r2dbc/r2dbc-postgresql/blob/8f9c7fecdb6c813fd2e85ce95d508a8e7a0adac7/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java#L225-L231)

**Comment by mirromutth** [comment]
This is my use error, it should be caused by the fact that I did not set ChannelPromise correctly.
