### ISSUE TITLE
The query does not support returning a null value

### ISSUE THREAD

**Issue by peacetrue** [mirromutth/r2dbc-mysql#180]
The case is  to query the maximum serial number.

When there is a record, there is no problem:

![image](https://user-images.githubusercontent.com/38878763/115982812-6ae36480-a5d0-11eb-8e83-4f24282105d9.png)

![image](https://user-images.githubusercontent.com/38878763/115982824-7c2c7100-a5d0-11eb-80dc-0324ba0627b4.png)

![image](https://user-images.githubusercontent.com/38878763/115982836-8b132380-a5d0-11eb-9cbf-4b66c0034367.png)

When there is no record, there is a problem:

![image](https://user-images.githubusercontent.com/38878763/115983289-e1816180-a5d2-11eb-8950-e0c58b06e516.png)

![image](https://user-images.githubusercontent.com/38878763/115983295-ecd48d00-a5d2-11eb-86ad-114d65f17f09.png)

The query does not support returning a null value.

![image](https://user-images.githubusercontent.com/38878763/115983371-450b8f00-a5d3-11eb-96f9-5d212c9faa52.png)

![image](https://user-images.githubusercontent.com/38878763/115983400-6cfaf280-a5d3-11eb-804c-7c2ae4969177.png)

**Comment by btakeya** [comment]
Hi @peacetrue , I think this issue is similar to #184 . Please note:)

**Comment by peacetrue** [comment]
see #184.
