### ISSUE TITLE
UDP ports exhaustion caused by vulnerable reactor-netty version

### ISSUE THREAD

**Issue by mibalan** [mirromutth/r2dbc-mysql#189]
### Current behavior

Long-running processes that use `r2dbc-mysql` in containers with a low ulimit can experience local UDP ports exhaustion, which in turn affects DNS resolution for all processes running on that machine.

This is caused by a file descriptor leak related to DNS resolution in the `reactor-netty` version referenced by `r2dbc-mysql` (via `reactor-bom`). The (buggy) `reactor-netty` version used by R2DBC-MySQL is `0.9.8.RELEASE`.

The corresponding issue in `reactor-netty` is https://github.com/reactor/reactor-netty/issues/1515

### Suggested fix

Update `reactor-netty` to at least version 1.0.5

**Comment by mirromutth** [comment]
Hi there, thanks a lot for your suggestion, apologies for the late reply.

I will upgrade `reactor-bom` to `2020.0.11`, which is in `reactor-netty:1.0.11`.
