### ISSUE TITLE
Implement ConnectionFactoryProvider

### ISSUE THREAD

**Issue by mirromutth** [mirromutth/r2dbc-mysql#19]
Implement `ConnectionFactoryProvider` and convert `ConnectionFactoryOptions` to `ConnectProperties` (maybe should change its name?)

The driver name is "mysql" which same to driver `jasync-sql`. Users should not reference multi-drives for the same database. @mp911de Or should I use a different driver name?

**Comment by mp911de** [comment]
There’s no central registry for driver names. I suggest sticking with mysql. This makes it easier to adapt JDBC-like URLs and with both drivers on the class path, one of the two drivers is activated.
