### ISSUE TITLE
Consider property `lastInsertId` of `OkMessage` to implement `returnGeneratedValues`

### ISSUE THREAD

**Issue by mirromutth** [mirromutth/r2dbc-mysql#21]
`lastInsertId` is a property in `OkMessage` (server-side message). After the client sends `INSERT` statement, it will be a generated value same as the value of `SELECT LAST_INSERT_ID()` result.

If last statement is not `INSERT`, this property will be `0` same as the value of `SELECT LAST_INSERT_ID()` result.

So, can just use `OkMessage.lastInsertId` to consider `returnGeneratedValues` implemented by the driver level, rather than `SELECT LAST_INSERT_ID()` which is the application level. This will improve the performance and *atomic* operation.

This is also more friendly to prepared statements because the prepared statements do **NOT** support batch statements which not like simple statements.

Of course, in MySQL driver, `returnGeneratedValues` will still support the last inserted ID only, not other fields.

**Comment by mp911de** [comment]
That sounds a neat optimization to reuse `OkMessage` and provide a synthetic `Row` from `lastInsertId` when enabling `returnGeneratedValues`.

**Comment by mirromutth** [comment]
It was completed, see `MySqlResult` and `MySqlResult.SyntheticRow`.
