### ISSUE TITLE
`RowMetadata` column names are case insensitive

### ISSUE THREAD

**Issue by mirromutth** [mirromutth/r2dbc-mysql#23]
`RowMetadata.getColumnMetadata` and `RowMetadata.getColumnNames` should support column metadata with name case insensitive.

> Drivers may enhance comparison sorting rules with escape characters to enforce a particular mode of comparison when querying for presence/absence of a column.

In addition, MySQL can execute a statement with special column names, which like `SELECT id AS Content, content FROM test` without backticks.

And MySQL will always return name without backticks in column metadata, so we do NOT know user execute the statement contains backticks or contains not.

@mp911de I will implement column name finding logic like follow:

```python
find column by name:
    if name enclosed by '`':
        remove first and last '`' from name
        if name in caseSensitiveMap:
            return the value of caseSensitiveMap found by name
        else throw the exception
    else:
        if name in caseSensitiveMap:
            return the value of caseSensitiveMap found by name
        else if name in caseInsensitiveMap:
            return the value of caseInsensitiveMap found by name
        else throw the exception
```

**Comment by mp911de** [comment]
Check out https://github.com/r2dbc/r2dbc-mssql/blob/master/src/main/java/io/r2dbc/mssql/MssqlRowMetadata.java and CollatedCollection for how it’s done in Postgres and SQL Server.

**Comment by mp911de** [comment]
BTW, users should not expect that lookup by name is escaped. That can be a convenience feature that is non-portable.

**Comment by mirromutth** [comment]
@mp911de I have a problem for this feature. If the user lookup by enclosed name, then means:

```java
String columnName = "`name`";

System.out.println(rowMetadata.getColumnNames().contain(columnName)); // must be false because MySQL returned name never contains backticks

System.out.println(rowMetadata.getColumnMetadata(columnName)); // maybe success
```

This is a very strange feature in my opinion: if the name is not an element in the `columnNames`, why I can get column metadata by this name?

**Comment by mirromutth** [comment]
Column name is already support case insensitive, see `MySqlColumnNames` and `CollatedColumnMetadata`.
