### ISSUE TITLE
Distribution of r2dbc-mysql

### ISSUE THREAD

**Issue by mp911de** [mirromutth/r2dbc-mysql#27]
How do you intend to ship r2dbc-mysql? I used a local build to test R2DBC MySQL with Spring Data (no obvious obstacles in our test suites so far, great job!).

You might want to consider https://jitpack.io/ for a start as that's a minimal-invasive way to provide at least snapshot builds.

**Comment by mirromutth** [comment]
@mp911de I have pushed it to a milestone version. And the `README` has updated yet.
