### ISSUE TITLE
Implement full authentication for "caching_sha2_password"

### ISSUE THREAD

**Issue by mirromutth** [mirromutth/r2dbc-mysql#31]
When SSL is enabled and the fast authentication phase fails, "caching_sha2_password" has a full authentication phase.

Currently, SSL has supported, should support full authentication of "caching_sha2_password" to better support for MySQL 8.x.

**Comment by mirromutth** [comment]
It should be support now, I will add unit tests for MySQL 8.x

**Comment by mirromutth** [comment]
It has supported in bc3dc8025023b066ebe097da7a26ffa9b1464464.

**Comment by hackdavid** [comment]
if you are facing "caching_sha2_password" error during connectivity of your mysql database using python ,
go through this
https://www.youtube.com/watch?v=YNq-EuQEJos
