### ISSUE TITLE
Add R2DBC TCK

### ISSUE THREAD

**Issue by mp911de** [mirromutth/r2dbc-mysql#35]
R2DBC provides a TCK (currently badly named) that can be integrated to verify driver compatibility:

* https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spi-test/src/main/java/io/r2dbc/spi/test/Example.java
* Implementation example: https://github.com/r2dbc/r2dbc-mssql/blob/master/src/test/java/io/r2dbc/mssql/MssqlExample.java

We will rename the `Example` class in a future release to `TestKit` (see https://github.com/r2dbc/r2dbc-spi/issues/93).

**Comment by mirromutth** [comment]
@mp911de I have a problem for `Example`, I see some unit tests like following:

```java
@Test
default void returnGeneratedValues() {
    // ...
    return Flux.from(statement
        .execute())
        .concatWith(close(connection))
        .flatMap(it -> it.map((row, rowMetadata) -> row.get(0)));
    // ...
}
```

Is it correctly? If the server does not respond to the result before the connection closed, the result will be aborted and does not contains any row. In my opinion, it should like that:

```java
return Flux.from(statement
    .execute())
    .flatMap(it -> it.map((row, rowMetadata) -> row.get(0)))
    .concatWith(close(connection));
```

**Comment by mp911de** [comment]
It would make sense to address the close ordering directly in R2DBC SPI. Feel free to submit a pull request. Currently, the setup works for H2, Postgres, SQL Server, and Google Spanner drivers.

**Comment by mirromutth** [comment]
Most of unit tests for TCK has passed on MySQL 5.5, 5.6, 5.7 and 8.0 except compound statement. I will support compound statement before third milestone.
