### ISSUE TITLE
r2dbc-mysql dependency not find

### ISSUE THREAD

**Issue by MonsterFlying** [mirromutth/r2dbc-mysql#47]
![image](https://user-images.githubusercontent.com/11550924/63141693-3e183500-c019-11e9-8233-a08fa3659313.png)

**Comment by mp911de** [comment]
Using Jitpack works for [us](https://github.com/spring-projects/spring-data-r2dbc/commit/e15e6b19d4919e120eac428f47062cc65a4b210b#diff-600376dffeb79835ede4a0b285078036R228).

**Comment by mirromutth** [comment]
Using Jitpack works for me, too.

No offense, but looks like you are networked from China, maybe you should to use **another way** for download this dependency? Of course, check if the local law allows before using any another way please.

**Comment by MonsterFlying** [comment]
thank you, Sure enough, the Internet was blocked!  But I solved the problem 。 An evil GWF!
