### ISSUE TITLE
dependency is not resolving and throwing error

### ISSUE THREAD

**Issue by nikkisingh111333** [mirromutth/r2dbc-mysql#51]
<dependency>
    <groupId>com.github.mirromutth</groupId>
    <artifactId>r2dbc-mysql</artifactId>
    <version>0.2.0.M2</version>
</dependency>
throwing:missing artifact com.github.mirromutth:r2dbc-mysql:jar:0.2.0.M2.
what to do ?

**Comment by mirromutth** [comment]
Sounds like same issue as #47 ?

**Comment by mirromutth** [comment]
Ping @nikkisingh111333 .

I have published `0.8.0.RC1` to the Maven Central Repository, see README please. If problem still exists, please reopen the issue.
