### ISSUE TITLE
MySqlConnectionFactoryProvider.supports(…) is too restrictive

### ISSUE THREAD

**Issue by mp911de** [mirromutth/r2dbc-mysql#56]
When attempting to obtain a `ConnectionFactory`, `MySqlConnectionFactoryProvider.supports(…)` checks for the existence of the user and host.

It would make sense to move these checks into the `create(…)` method. Although the a connection cannot be established, users do not get sufficient information about what they did wrong or what they can do in order to fix the issue.

By catching missing host and username in `MySqlConnectionFactoryProvider.create(…)`, we could use `options.getRequiredValue(…)`. If no value is configured, then that method would throw `IllegalStateException` along with a proper error message (`No value found for %s`) and users can fix their setup.

```
java.lang.IllegalStateException: Unable to create a ConnectionFactory for 'ConnectionFactoryOptions{options={host=localhost, driver=mysql}}'. Available drivers: [ mysql ]
```

**Comment by mirromutth** [comment]
It solved by PR #61 , target version is 0.3.0.M3.
