### ISSUE TITLE
Consider publishing snapshot artifacts to Maven Central

### ISSUE THREAD

**Issue by mp911de** [mirromutth/r2dbc-mysql#58]
It would make sense to deploy snapshot builds to oss.sonatype.org and in the long term, to Maven Central (once a release is available).

You can find the guide to get credentials for Sonatype here: https://central.sonatype.org/pages/ossrh-guide.html

This is, to simplify the consumption of the artifacts as Jitpack requires an additional repository to be included in each project.

**Comment by mirromutth** [comment]
I have published BUILD-SNAPSHOT to sonatype snapshots repository.

This issue will be keep until the distribution of first release candidate.

**Comment by mirromutth** [comment]
The `0.8.0.RC1` is already available in Central Repository, see README.
