### ISSUE TITLE
r2dbc-spi dependency not found

### ISSUE THREAD

**Issue by likaiwalkman** [mirromutth/r2dbc-mysql#7]
below dependency not found:
  <r2dbc-spi.version>**1.0.0.BUILD-SNAPSHOT**</r2dbc-spi.version>,
where can I find this artifact?

official maven repo only keeps version of '**1.0.0.M7**' :(

**Comment by mp911de** [comment]
Snapshots are available from https://repo.spring.io/snapshot/ and milestones from https://repo.spring.io/milestone/. Btw. 0.8.0 M8 is out, I filed #8.
