### ISSUE TITLE
Memory leak when user consume only a portion rows

### ISSUE THREAD

**Issue by mirromutth** [mirromutth/r2dbc-mysql#84]
It was broken by #74 . This problem exists when I moved `dicardOnCancel` from `MySqlResult` to `QueryFlow`.

The `windowUntil` will pre-fetch messages, so some messages may be requested and cached by `FluxWindowPredicate`,  but they does not be consumed by `Result`. (because user ignored `Result`)

**Comment by mp911de** [comment]
Note: Not consuming a `Result` is a bug in how the API is used (`statement.execute().then()` should not be used as per R2DBC Spec. Drivers may apply `doOnDiscard(…)` to handle dropped elements).

**Comment by mirromutth** [comment]
Understood, but memory leak also exists when user consume only a portion rows, so I have to recover the line of `discardOnCancel` in `MySqlResult`.

**Comment by mirromutth** [comment]
It solved by a64ca3a612203267cfc52c1704c31d96058bf9a0 and published to `0.8.0.BUILD-SNAPSHOT`, target version is `0.8.0.RELEASE`.
