### ISSUE TITLE
Timestamp appears to lose millisecond precision when decoded as text

### ISSUE THREAD

**Issue by maccamlcQ** [mirromutth/r2dbc-mysql#89]
I don't understand the full inner workings of MySQL. However, I have noticed that using Spring Data R2DBC with this driver, I find that a type of LocalDateTime is losing the millisecond precision.

My findings with value `2019-12-09 12:54:48.698`:

* Written as expected using LocalDateTimeCodec and I see it in the database
* However when it is read back using the R2dbcRepository#findAll in Spring Data it returns `2019-12-09T12:54:48`

I traced this to LocalDateTimeCodec#decodeText which calls LocalTimeCodec#readTimeText where the nanoseconds are not considered, unlike with decodeBinary.

Is this on purpose, or the nanosecond precision should be available by both binary and text decode mode?

**Comment by mirromutth** [comment]
See https://github.com/mirromutth/r2dbc-mysql/tree/master#before-use .

> The MySQL return microseconds when only in prepared statement result (and maybe has not microsecond even in prepared statement result). Therefore this driver does not guarantee time accuracy to microseconds.

**Comment by maccamlcQ** [comment]
Thanks for the response and explanation. Appreciate it.

I will update the application to work with time values up to seconds only. That precision will be enough for my scenario :)

**Comment by mp911de** [comment]
Would it make sense to add a configuration property (`Predicate<String> preferPreparedStatement`) to enforce prepared statement usage? We have a similar feature in R2DBC MS SQL although there we control cursor execution (https://github.com/r2dbc/r2dbc-mssql/blob/master/src/main/java/io/r2dbc/mssql/MssqlConnectionConfiguration.java#L67)

**Comment by mirromutth** [comment]
This is a problem that can only be solved by the MySQL server-side. The driver can not get more precision than seconds when server does not return it. Even in binary-based queries, server will not return. Seems to be related to server startup options or compilation options, and the default behavior does not return.

Although it does not solve this problem, I have created a new issue for the option of `preferPreparedStatement`, see #96. It will be useful when server supports/enabled more time precision in binary-based queries.

Therefore, I closed this issue. If you have any questions about this issue, reopen and comment please.
