### ISSUE TITLE
Support client side (emulated) prepared statements 

### ISSUE THREAD

**Issue by vuck3o** [mirromutth/r2dbc-mysql#92]
My team is using **Vitess** as a solution for scaling MySql horizontality, of course with the help of mysql jdbc.
We are going in the direction of switching to a reactive stack and we tested **spring-data-r2dbc** + **r2dbc-mysql**.
Vitess has a mysql server implementation, but not completely.

Communication between this driver and Vitess was very good until we tested the prepared statements. Vitess doesn't support **server-side prepared statements**, as I can see, they were implemented here https://github.com/mirromutth/r2dbc-mysql/issues/4.

Vitess team had a similar report, and it looks like this feture will not be supported by them.
https://github.com/vitessio/vitess/issues/4386

I also think it would be useful to have a configuration option, similar to existing mysql jdbc `useServerPrepStmts` configuration option.
It's left to the user to choose whether to use server side, or to save one database roundtrip and use client side prepared statements.
https://vladmihalcea.com/how-does-the-mysql-jdbc-driver-handle-prepared-statements/

Also `useServerPrepStmts` is `false` by default for mysql jdbc, apparently here is equal to `true`, which is a change in behaviour for users who make migration from jdbc to reactive stack.

**Comment by mirromutth** [comment]
Hi there, thanks for the report, sorry for my late reply.

I try to support it on #97 . Now it can configured on `useClientPrepareStatement` and `useServerPrepareStatement` in PR.

But I'm not sure the configuration should be changed to client-preparing or just keep it as.

**Comment by vuck3o** [comment]
> But I'm not sure the configuration should be changed to client-preparing or just keep it as.

Since SPI does not obligate or prescribe default behavior in this case, then it is up to you to decide what will be set as default. Also documentation should be updated accordingly.

Btw thanks for the feature :rocket:

**Comment by vuck3o** [comment]
@mirromutth When can we expect the release of version 0.8.1?

**Comment by mirromutth** [comment]
Roadmap:
- Add more unit tests for this feature and #96 .
- Refactor integration tests, simplify those and split each MySQL version to each script instead of a large CI (it's named `build` now).
- Finish #87 , not sure, but it seems like a bug.
- The next release is supposed to be early February, when there are no more major bugs.

**Comment by mirromutth** [comment]
It is supported by PR and published to `0.8.1.BUILD-SNAPSHOT`. Target version is `0.8.1.RELEASE`.

> If want to use snapshot versions, add Sonatype snapshots repository to Maven file, see also README

**Comment by vuck3o** [comment]
Great, I can confirm that it works, thanks :tada:
